spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE  # Usa o H2 em memória
    driverClassName: org.h2.Driver
    username: sa  # Usuário padrão do H2
    password: password  # Senha padrão do H2 (ajuste conforme necessário)
    hikari:
      pool-name: H2TestPool  # Nome da pool de conexões
      maximum-pool-size: 10  # Limite de conexões no pool
  h2:
    console:
      enabled: true  # Habilita o console web do H2 para acesso via navegador
      path: /h2-console  # Caminho do console (exemplo: http://localhost:8080/h2-console)
  jpa:
    hibernate:
      ddl-auto: create-drop  # Garante que o banco de dados será recriado a cada teste
    database-platform: org.hibernate.dialect.H2Dialect  # Dialeto do H2
    show-sql: true  # Mostra as consultas SQL no log durante os testes
    generate-ddl: true  # Gera automaticamente o DDL baseado nas entidades
    defer-datasource-initialization: true
  test:
    enabled: true  # Garante que as configurações sejam usadas apenas em testes
  flyway:
    enabled: false