
server:
  port: 8080
  servlet:
    context-path: /api/v1
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # Comma-separated list of MIME types that should be compressed.
    min-response-size: 1024
  undertow:
    threads:
      worker: 40
      io: 4
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2MB
  profiles:
    active: default
  flyway:
    enabled: true
    locations: classpath:db/migration
  application:
    name: recipe-service
  datasource:
    url: jdbc:postgresql://${DB_HOST_NAME_PROD}:${DB_PORT_PROD:5433}/${DB_NAME_PROD}
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 20
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true

  jackson:
    deserialization:
      fail-on-ignored-properties: true
      fail-on-unknown-properties: true



  mvc:
    throw-exception-if-no-handler-found: true
aws:
  s3:
    access: ${AWS_ACCESS_KEY_ID}
    secret: ${AWS_SECRET_ACCESS_KEY}
    bucket: ${AWS_RECIPE_APP_BUCKET}
    region: sa-east-1