version: '3.8'

services:
  app:
    container_name: recipe-hub-container
    build: .
#    image: soapbody/recipe-service:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - recipe_hub_networks

  postgres:
    image: postgres:14
    container_name: recipe-hub-postgres-container
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INIT_DB_ARGS: "--encoding=UTF8 --locale=pt_BR.UTF-8"
    ports:
      - "5433:5432"
    networks:
      - recipe_hub_networks
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  recipe_hub_networks: {}
