
services:
  app:
    container_name: recipe-hub-app-container
    build: .
    #    image: soapbody/recipe-service:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - recipe_hub_networks
  postgres:
    image: postgres:14
    container_name: recipe-hub-postgres-container
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME_PROD}
      POSTGRES_PASSWORD: ${DB_PASSWORD_PROD}
      POSTGRES_DB: ${DB_NAME_PROD}
    ports:
      - "5433:5432"
    networks:
      - recipe_hub_networks
    volumes:
      - ./data/prod:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  recipe_hub_networks: {}
