name: CI Pipeline

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
  workflow_dispatch:

jobs:
  tests:
    name: Run tests and build Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven (skip tests)
        run: mvn clean install -DskipTests

      # Adicionando etapa para modificar docker-compose.yml
      - name: Modify docker-compose.yml for CI/CD
        run: |
          sed -i 's/#    image: soapbody\/recipe-service:latest/image: soapbody\/recipe-service:latest/' docker-compose.yml
          sed -i 's/  build: ./  # build: ./g' docker-compose.yml

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_NAME }}/recipe-service:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_NAME }}/recipe-service:latest
